# Generated by Django 5.1.3 on 2024-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='managing',
            field=models.BooleanField(default=False, help_text='Select if you or your company is managing this building'),
        ),
        migrations.AddField(
            model_name='estate',
            name='managing',
            field=models.BooleanField(default=False, help_text='Select if you or your company is managing this estate'),
        ),
    ]
