# Generated by Django 5.1.3 on 2024-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_building_managing_estate_managing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
