# Generated by Django 5.1.3 on 2024-12-02 19:39

import django.db.models.deletion
import myrealestate.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0003_alter_building_address_alter_estate_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=myrealestate.properties.models.property_image_path, validators=[myrealestate.properties.models.validate_file_size])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('estate', 'building', 'unit', 'subunit')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='properties__content_1cca38_idx'), models.Index(fields=['is_primary'], name='properties__is_prim_893694_idx'), models.Index(fields=['order'], name='properties__order_99feac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id', 'is_primary'), name='unique_primary_image_per_object')],
            },
        ),
    ]
