# Generated by Django 5.1.3 on 2024-12-03 19:59

import myrealestate.common.storage
import myrealestate.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(storage=myrealestate.common.storage.CustomS3Boto3Storage(), upload_to=myrealestate.properties.models.property_image_path, validators=[myrealestate.properties.models.validate_file_size]),
        ),
    ]
