# Generated by Django 5.1.3 on 2025-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Icon identifier for frontend', max_length=50)),
                ('category', models.CharField(help_text='Category for grouping amenities', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='estate',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='features',
        ),
        migrations.CreateModel(
            name='EstateAmenityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_relations', to='properties.estate')),
            ],
            options={
                'unique_together': {('estate', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='UnitAmenityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(blank=True, help_text='Additional details about this amenity', max_length=255)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_relations', to='properties.unit')),
            ],
            options={
                'unique_together': {('unit', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.ManyToManyField(related_name='units', through='properties.UnitAmenityRelation', to='properties.amenity'),
        ),
        migrations.CreateModel(
            name='UnitFeatureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyfeature')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_relations', to='properties.unit')),
            ],
            options={
                'unique_together': {('unit', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='amenities',
            field=models.ManyToManyField(related_name='estates', through='properties.EstateAmenityRelation', to='properties.amenity'),
        ),
        migrations.AddField(
            model_name='unit',
            name='features',
            field=models.ManyToManyField(related_name='units', through='properties.UnitFeatureRelation', to='properties.propertyfeature'),
        ),
    ]
