# Generated by Django 5.1.3 on 2025-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('trading_name', models.CharField(blank=True, max_length=255, verbose_name='Trading Name')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration Number')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax/VAT Number')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Business Email')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Support Email')),
                ('accounts_email', models.EmailField(blank=True, max_length=254, verbose_name='Accounts Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
