# Generated by Django 5.1.3 on 2024-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company Settings', 'verbose_name_plural': 'Company Settings'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='company',
            name='accounts_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Accounts Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Business Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tax/VAT Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Trading Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
