# Generated by Django 5.1.3 on 2024-12-07 14:52

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for row in User.objects.all():
        row.email_verification_token = uuid.uuid4()
        row.save(update_fields=["email_verification_token"])    

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verification_token_user_email_verified'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
    ]
